"""Update models for DSCS integration

Revision ID: 1a2928c73e2e
Revises: 
Create Date: 2025-03-20 00:39:10.766803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2928c73e2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('challenge_count', sa.Integer(), nullable=False),
    sa.Column('verification_result', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('granted_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_access_record_granted_by_user', 'user', ['granted_by'], ['id'])


    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dscs_file_id', sa.String(length=255), nullable=True))

    with op.batch_alter_table('metadata_vector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_metadata_vector_file_id_file', 'file', ['file_id'], ['id'])



    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dscs_user_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dscs_user_id')

    with op.batch_alter_table('metadata_vector', schema=None) as batch_op:
        batch_op.drop_constraint('fk_metadata_vector_file_id_file', type_='foreignkey')
        batch_op.drop_constraint('fk_access_record_granted_by_user', type_='foreignkey')
        batch_op.drop_column('file_id')

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('dscs_file_id')

    with op.batch_alter_table('access_record', schema=None) as batch_op:
        batch_op.drop_constraint('fk_metadata_vector_file_id_file', type_='foreignkey')
        batch_op.drop_constraint('fk_access_record_granted_by_user', type_='foreignkey')
        batch_op.drop_column('granted_by')
        batch_op.drop_column('granted_at')

    op.drop_table('verification_log')
    # ### end Alembic commands ###
